function [fitresult, gof] = createFit(xMean, meanPulse)
%CREATEFIT(XMEAN,MEANPULSE)
%  Create a fit.
%
%  Data for 'erfc_inv_sqrt' fit:
%      X Input : xMean
%      Y Output: meanPulse
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 27-Sep-2016 23:06:02


%% Fit: 'erfc_inv_sqrt'.
[xData, yData] = prepareCurveData( xMean, meanPulse );

% Set up fittype and options.
ft = fittype( 'a*erfc(b/sqrt(c*x))+d', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.94673255346855 0.191908364958941 0.608192833325577 0.278498218867048];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
% % 
% % % Plot fit with data.
% % figure( 'Name', 'erfc_inv_sqrt' );
% % h = plot( fitresult, xData, yData );
% % legend( h, 'meanPulse vs. xMean', 'erfc_inv_sqrt', 'Location', 'NorthEast' );
% % % Label axes
% % xlabel xMean
% % ylabel meanPulse
% % grid on


