function [fitresult, gof] = createFit(xMean, meanPulse)
%CREATEFIT(XMEAN,MEANPULSE)
%  Create a fit.
%
%  Data for 'erfc_sqrt_x' fit:
%      X Input : xMean
%      Y Output: meanPulse
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Sep-2016 22:57:31


%% Fit: 'erfc_sqrt_x'.
[xData, yData] = prepareCurveData( xMean, meanPulse );

% Set up fittype and options.
ft = fittype( 'a*erfc(-sqrt(b*x))+c', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.584545301954375 0.452249270150983 0.475636782640328];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'erfc_sqrt_x' );

% Plot fit with data.
subplot( 2, 1, 1 );
plot( fitresult, xData, yData );
% Label axes
xlabel xMean
ylabel meanPulse
grid off

% Plot residuals.
subplot( 2, 1, 2 );
plot( fitresult, xData, yData, 'residuals' );
% Label axes
xlabel xMean
ylabel meanPulse
grid off


