function [fitresult, gof] = createFit(timeMean, correctedRx)
%CREATEFIT(TIMEMEAN,CORRECTEDRX)
%  Create a fit.
%
%  Data for 'erfc_sqrt' fit:
%      X Input : timeMean
%      Y Output: correctedRx
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 11-Oct-2016 23:18:06


%% Fit: 'erfc_sqrt'.
[xData, yData] = prepareCurveData( timeMean, correctedRx );

% Set up fittype and options.
ft = fittype( 'a*erfc(b/sqrt(c*x))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [0.00115251106722081 0.779103974566464 0.718306235347856];
opts.Upper = [10 10 10];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'erfc_sqrt' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult, xData, yData );
legend( h, 'correctedRx vs. timeMean', 'erfc_sqrt', 'Location', 'NorthEast' );
% Label axes
xlabel timeMean
ylabel correctedRx
grid off

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult, xData, yData, 'residuals' );
legend( h, 'erfc_sqrt - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel timeMean
ylabel correctedRx
grid off


